### ISSUE TITLE
Unrecognized casadiMex with ARM version MATLAB 2023b or later

### ISSUE THREAD

**Issue by yuefan98** [COBRAPROsimulator/COBRAPRO#1]
I followed the installation guide and got the output for a successful installation on ARM version MATLAB 2023b and 2024a. However, I encountered issues with casadiMex and was unable to run the code with these two versions of MATLAB.

The installation and operation work with intel version MATLAB 2022b running on the same Mac with an arm chip. This is likely an issue with the arm version of MATLAB, so it might be worth troubleshooting or at least mentioning it in the known issues section.  
<img width="628" alt="Pasted Graphic" src="https://github.com/COBRAPROsimulator/COBRAPRO/assets/97193085/c8e2ba7f-7096-45c1-998a-00c30b8c552c">

**Comment by COBRAPROsimulator** [comment]
Hi @yuefan98, thank you for pointing this out. Could you clarify what you mean by the "ARM version MATLAB 2023b and 2024a"?

**Comment by yuefan98** [comment]
Yes, here is the screenshot of the Matlab versions that are available from the website for the latest release. MATLAB can now run natively on Apple silicon, which is based on ARM architecture, but that seems to cause a problem with casadiMex. I don't know why that is the case. So it might be worth troubleshooting or at least mentioning in the documentation. The code can run without any problem with MATLAB 2022a (developed for intel processor) with the same mac I have with Apple silicon processor. 
<img width="863" alt="image" src="https://github.com/COBRAPROsimulator/COBRAPRO/assets/97193085/6621c79d-c2a9-4ef9-bafd-8320d81bb6fb">

**Comment by COBRAPROsimulator** [comment]
Thank you for clarifying @yuefan98. Really appreciate you pointing out this issue. I will add to the known issues in the README page.

**Comment by COBRAPROsimulator** [comment]
Hi @yuefan98, upon further investigation, I am re-visiting this thread.

For Macs with Apple silicon processor, I noticed the issue is with the CasADi version. There are two versions of the Mac M1 version of [CasADi for MATLAB](https://web.casadi.org/get/): Option 1. R2020b or later and Option 2. R2018b or later. When I use the first option (R2020b or later), I get the same error you got "Unrecognized variable or function  <img width="920" alt="Screenshot 2024-09-22 at 1 48 05 PM" src="https://github.com/user-attachments/assets/a6e5be15-8626-4202-8a93-128be501c501">  However, if I use the second version, R2018b or later, CasADi seems to work fine for MATLAB 2023b, 2024a, 2024b (ARM/Apple Silicon versions of MATLAB). 

If possible, could you please confirm if this is also true for your Mac with the Apple Silicon chip? Thank you so much.

<img width="920" alt="Screenshot 2024-09-22 at 1 48 05 PM" src="https://github.com/user-attachments/assets/86c32a3c-8e11-454e-84a9-27b228da1aa8">
 you please

**Comment by yuefan98** [comment]
Thanks for checking back on this. It works on my side now with option 2 installed for the Apple Silicon processor. For your reference, the version I am using is the following _casadi-3.6.6-osx_arm64-matlab2018b_

**Comment by COBRAPROsimulator** [comment]
@yuefan98, thanks so much for confirming. I will update the README file accordingly, notifying that for Mac Silicon users Option 2 should be used for CasADi.
